
build:
  pythonVersion: 3.10

services:
  - type: web
    name: django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn movie_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: movie_project.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: ALLOWED_HOSTS
        value: your-app-name.onrender.com
